---

- hosts: all
  become: true
  tasks:

  - name: Update Machines (Ubuntu)
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update Machines (Debian)
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

# add qemu agent to vms 
  - name: Add QMU agent to VMs
    package:
      name: qemu-guest-agent
    when: ansible_virtualization_type == "kvm"