---

- hosts: all
  become: true
  tasks:

  - name: Update Machines
    apt:
      update_cache: yes
    when: ansible_distribution_version in ["Debian", "Ubuntu"]

# add qemu agent to vms 
  - name: Add QMU agent to VMs
    apt:
      name: qemu-guest-agent
    when: ansible_virtualization_type == "kvm"