# use for ansible pull for new builds

- hosts: localhost
  connection: local
  become: true

# add packages to be install
  tasks:

  - name: Update Machines (Ubuntu)
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update Machines (Debian)
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"
    
  - name: Install packages
    package:
       name:
        - htop
        - mc
        - apt-transport-https
        - curl
        - software-properties-common
       state: present

  - name: Add VSCode GPG apt Key
    apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

  - name: Add VSCode Repository
    apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

  - name: Update apt packages
    apt:
      update_cache: "yes"
      force_apt_get: "yes"

  - name: Install VSCode
    apt:
      name: "code"
      state: present
      force_apt_get: "yes"