# use for ansible pull for new builds

- hosts: localhost
  connection: local
  become: true

# add packages to be install
  tasks:
  - name: Install packages
    package:
       name:
        - htop
        - mc